### ISSUE TITLE
Would you mind a slight modification so that users with lower version of node.js (e.g. v12) can also use it?

### ISSUE THREAD

**Issue by foresightyj** [Shinigami92/vite-ts-nameof#47]
Right now, it throws the following error in my machine as I am stuck with node version `v12.14.1` because my dev machine is still win7 which does not support node v14 at this moment.

Just change `code = fileText ?? code;` to `code = fileText? fileText: code;`, or adjust your tsconfig.json so that it emits more compatible js.

Thanks if you can consider. And thanks for the library by the way. I am a big fan of ts-nameof and this plugin really solves my problem.

```
error when starting dev server:
D:\Working\fht-management-midway-hooks\node_modules\_vite-plugin-ts-nameof@1.0.0@vite-plugin-ts-nameof\lib\index.js:14
                code = fileText ?? code;
                                 ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Working\fht-management-midway-hooks\vite.config.ts:32:47)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.require.extensions.<computed> [as .ts] (D:\Working\fht-management-midway-hooks\node_modules\_vite@2.3.8@vite\dist\node\chunks\dep-0ed4fbc0.js:72082:20)
    at Module.load (internal/modules/cjs/loader.js:811:32)
```

**Comment by Shinigami92** [comment]
Released as [v1.0.1](https://www.npmjs.com/package/vite-plugin-ts-nameof/v/1.0.1)
